### Objective
The objective of this notebook is to import the cleaned UPI datasets into a MySQL database and verify successful data ingestion. This notebook demonstrates the ETL (Extract, Transform, Load) process by reading CSV files using Python, performing necessary preprocessing, and loading the data into SQL tables for further analysis.

### Tools Used
- Python
- Pandas
- MySQL
- SQLAlchemy
- PyMySQL

### Workflow
1. Import required libraries
2. Read CSV datasets
3. Perform basic data cleaning and preprocessing
4. Connect Python to MySQL
5. Create SQL tables (already created using DDL scripts in MySQL)
6. Import datasets into SQL
7. Validate imported records
8. Verify row counts and data integrity

In [ ]:
import pandas as pd

In [2]:
df = pd.read_csv(r"C:\Users\ADMIN\Downloads\4414701-Datasets_-_UPI_Transactions_Data_Analysis\customer_master.csv")

In [3]:
df.head()

,customer_id,full_name,mobile_number,age,gender,region,date_joined,is_business_user,risk_score
0,cust100000,Ryan Gallagher,7631706690,26,female,north,2024-01-28,False,0.39
1,cust100001,Robert Garza,806360837,49,female,west,2025-04-16,False,0.13
2,cust100002,Haley Rhodes,8124158683,68,male,west,2022-02-10,True,0.14
3,cust100003,Sonya Mathis,3662585178,42,male,north,2021-02-18,False,0.07
4,cust100004,Ryan Wood,9996228303,35,female,south,2023-04-17,False,0.30

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 9 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   customer_id       10000 non-null  object
 1   full_name         10000 non-null  object
 2   mobile_number     10000 non-null  int64
 3   age               10000 non-null  int64
 4   gender            10000 non-null  object
 5   region            10000 non-null  object
 6   date_joined       10000 non-null  object
 7   is_business_user  10000 non-null  bool
 8   risk_score        10000 non-null  float64
dtypes: bool(1), float64(1), int64(2), object(5)
memory usage: 634.9+ KB

In [6]:
df.shape

(10000, 9)

In [7]:
import mysql.connector

ModuleNotFoundError: No module named 'mysql'

In [8]:
!pip install mysql-connector-python

Collecting mysql-connector-python
  Downloading mysql_connector_python-9.7.0-cp313-cp313-win_amd64.whl.metadata (11 kB)
Downloading mysql_connector_python-9.7.0-cp313-cp313-win_amd64.whl (17.7 MB)
   ---------------------------------------- 0.0/17.7 MB ? eta -:--:--
   ---------------------------------------- 0.0/17.7 MB ? eta -:--:--
   ---------------------------------------- 0.0/17.7 MB ? eta -:--:--
   ---------------------------------------- 0.0/17.7 MB ? eta -:--:--
   ---------------------------------------- 0.0/17.7 MB ? eta -:--:--
    --------------------------------------- 0.3/17.7 MB ? eta -:--:--
    --------------------------------------- 0.3/17.7 MB ? eta -:--:--
   - -------------------------------------- 0.5/17.7 MB 465.8 kB/s eta 0:00:37
   - -------------------------------------- 0.5/17.7 MB 465.8 kB/s eta 0:00:37
   - -------------------------------------- 0.5/17.7 MB 465.8 kB/s eta 0:00:37
   - -------------------------------------- 0.5/17.7 MB 465.8 kB/s eta 0:00:37
   - -------------------------------------- 0.5/17.7 MB 465.8 kB/s eta 0:00:37
   - -------------------------------------- 0.5/17.7 MB 465.8 kB/s eta 0:00:37
   - -------------------------------------- 0.8/17.7 MB 297.4 kB/s eta 0:00:57
   -- ------------------------------------- 1.0/17.7 MB 389.1 kB/s eta 0:00:43
   --- ------------------------------------ 1.6/17.7 MB 575.7 kB/s eta 0:00:28
   ---- ----------------------------------- 1.8/17.7 MB 659.0 kB/s eta 0:00:25
   ----- ---------------------------------- 2.4/17.7 MB 784.2 kB/s eta 0:00:20
   ------ --------------------------------- 2.9/17.7 MB 901.5 kB/s eta 0:00:17
   ------ --------------------------------- 2.9/17.7 MB 901.5 kB/s eta 0:00:17
   ------ --------------------------------- 2.9/17.7 MB 901.5 kB/s eta 0:00:17
   ------ --------------------------------- 2.9/17.7 MB 901.5 kB/s eta 0:00:17
   ------- -------------------------------- 3.1/17.7 MB 759.8 kB/s eta 0:00:20
   ------- -------------------------------- 3.1/17.7 MB 759.8 kB/s eta 0:00:20
   ------- -------------------------------- 3.1/17.7 MB 759.8 kB/s eta 0:00:20
   ------- -------------------------------- 3.1/17.7 MB 759.8 kB/s eta 0:00:20
   ------- -------------------------------- 3.4/17.7 MB 693.1 kB/s eta 0:00:21
   -------- ------------------------------- 3.7/17.7 MB 719.9 kB/s eta 0:00:20
   -------- ------------------------------- 3.7/17.7 MB 719.9 kB/s eta 0:00:20
   -------- ------------------------------- 3.9/17.7 MB 702.7 kB/s eta 0:00:20
   -------- ------------------------------- 3.9/17.7 MB 702.7 kB/s eta 0:00:20
   --------- ------------------------------ 4.2/17.7 MB 697.2 kB/s eta 0:00:20
   ---------- ----------------------------- 4.5/17.7 MB 715.0 kB/s eta 0:00:19
   ----------- ---------------------------- 5.0/17.7 MB 773.3 kB/s eta 0:00:17
   ------------ --------------------------- 5.5/17.7 MB 824.6 kB/s eta 0:00:15
   ------------- -------------------------- 5.8/17.7 MB 850.3 kB/s eta 0:00:15
   -------------- ------------------------- 6.3/17.7 MB 891.5 kB/s eta 0:00:13
   -------------- ------------------------- 6.6/17.7 MB 901.2 kB/s eta 0:00:13
   -------------- ------------------------- 6.6/17.7 MB 901.2 kB/s eta 0:00:13
   -------------- ------------------------- 6.6/17.7 MB 901.2 kB/s eta 0:00:13
   -------------- ------------------------- 6.6/17.7 MB 901.2 kB/s eta 0:00:13
   -------------- ------------------------- 6.6/17.7 MB 901.2 kB/s eta 0:00:13
   --------------- ------------------------ 6.8/17.7 MB 816.0 kB/s eta 0:00:14
   --------------- ------------------------ 6.8/17.7 MB 816.0 kB/s eta 0:00:14
   ---------------- ----------------------- 7.1/17.7 MB 804.4 kB/s eta 0:00:14
   ---------------- ----------------------- 7.3/17.7 MB 819.0 kB/s eta 0:00:13
   ----------------- ---------------------- 7.6/17.7 MB 835.4 kB/s eta 0:00:13
   ----------------- ---------------------- 7.9/17.7 MB 842.6 kB/s eta 0:00:12
   ------------------ --------------------- 8.4/17.7 MB 877.9 kB/s eta 0:00:11
   ------------------- -------------------- 8.7/17.7 MB 894.1 kB/s eta 0:00:11
   -------------------- ------------------- 8.9/17.7 MB 890.3 kB/s eta 0:00:10
   -------------------- ------------------- 9.2/17.7 MB 902.2 kB/s eta 0:00:10
   --------------------- ------------------ 9.4/17.7 MB 915.6 kB/s eta 0:00:10
   ---------------------- ----------------- 10.0/17.7 MB 931.3 kB/s eta 0:00:09
   ---------------------- ----------------- 10.0/17.7 MB 931.3 kB/s eta 0:00:09
   ---------------------- ----------------- 10.0/17.7 MB 931.3 kB/s eta 0:00:09
   ----------------------- ---------------- 10.2/17.7 MB 909.0 kB/s eta 0:00:09
   ----------------------- ---------------- 10.2/17.7 MB 909.0 kB/s eta 0:00:09
   ------------------------ --------------- 10.7/17.7 MB 916.7 kB/s eta 0:00:08
   ------------------------- -------------- 11.3/17.7 MB 944.0 kB/s eta 0:00:07
   ------------------------- -------------- 11.3/17.7 MB 944.0 kB/s eta 0:00:07
   -------------------------- ------------- 11.5/17.7 MB 941.9 kB/s eta 0:00:07
   -------------------------- ------------- 11.5/17.7 MB 941.9 kB/s eta 0:00:07
   -------------------------- ------------- 11.5/17.7 MB 941.9 kB/s eta 0:00:07
   -------------------------- ------------- 11.5/17.7 MB 941.9 kB/s eta 0:00:07
   --------------------------- ------------ 12.1/17.7 MB 912.2 kB/s eta 0:00:07
   ---------------------------- ----------- 12.6/17.7 MB 936.3 kB/s eta 0:00:06
   ----------------------------- ---------- 12.8/17.7 MB 942.7 kB/s eta 0:00:06
   ----------------------------- ---------- 13.1/17.7 MB 954.1 kB/s eta 0:00:05
   ------------------------------ --------- 13.4/17.7 MB 959.6 kB/s eta 0:00:05
   ------------------------------ --------- 13.4/17.7 MB 959.6 kB/s eta 0:00:05
   ------------------------------- -------- 13.9/17.7 MB 957.1 kB/s eta 0:00:04
   ------------------------------- -------- 13.9/17.7 MB 957.1 kB/s eta 0:00:04
   -------------------------------- ------- 14.2/17.7 MB 954.2 kB/s eta 0:00:04
   -------------------------------- ------- 14.2/17.7 MB 954.2 kB/s eta 0:00:04
   -------------------------------- ------- 14.4/17.7 MB 945.1 kB/s eta 0:00:04
   -------------------------------- ------- 14.4/17.7 MB 945.1 kB/s eta 0:00:04
   -------------------------------- ------- 14.4/17.7 MB 945.1 kB/s eta 0:00:04
   --------------------------------- ------ 14.7/17.7 MB 920.5 kB/s eta 0:00:04
   ---------------------------------- ----- 15.2/17.7 MB 936.5 kB/s eta 0:00:03
   ---------------------------------- ----- 15.5/17.7 MB 939.3 kB/s eta 0:00:03
   ----------------------------------- ---- 15.7/17.7 MB 942.7 kB/s eta 0:00:03
   ------------------------------------ --- 16.0/17.7 MB 955.3 kB/s eta 0:00:02
   ------------------------------------ --- 16.0/17.7 MB 955.3 kB/s eta 0:00:02
   ------------------------------------ --- 16.0/17.7 MB 955.3 kB/s eta 0:00:02
   ------------------------------------ --- 16.3/17.7 MB 930.8 kB/s eta 0:00:02
   ------------------------------------- -- 16.5/17.7 MB 932.6 kB/s eta 0:00:02
   -------------------------------------- - 17.0/17.7 MB 947.9 kB/s eta 0:00:01
   ---------------------------------------  17.6/17.7 MB 964.0 kB/s eta 0:00:01
   ---------------------------------------- 17.7/17.7 MB 964.2 kB/s  0:00:18
Installing collected packages: mysql-connector-python
Successfully installed mysql-connector-python-9.7.0

In [9]:
import mysql.connector

In [20]:
import mysql.connector

conn = mysql.connector.connect(
    host="localhost",
    user="root",
    password="Shreyassneha@1303",
    database="upi_transaction_analysis"
)

print("✅ Connected to MySQL successfully!")

✅ Connected to MySQL successfully!

In [21]:
cursor = conn.cursor()

print("Cursor created successfully!")

Cursor created successfully!

In [22]:
insert_query = """
INSERT INTO customer_master
(customer_id, full_name, mobile_number, age, gender, region,
 date_joined, is_business_user, risk_score)
VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s)
"""

In [23]:
first_row = tuple(df.iloc[0])

print(first_row)

('cust100000', 'Ryan Gallagher', np.int64(7631706690), np.int64(26), 'female', 'north', '2024-01-28', np.False_, np.float64(0.39))

In [25]:
print(df.dtypes)

customer_id          object
full_name            object
mobile_number         int64
age                   int64
gender               object
region               object
date_joined          object
is_business_user       bool
risk_score          float64
dtype: object

In [26]:
print(type(first_row[2]))
print(type(first_row[3]))
print(type(first_row[8]))

<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.float64'>

In [28]:
first_row = (
    str(df.iloc[0]["customer_id"]),
    str(df.iloc[0]["full_name"]),
    str(df.iloc[0]["mobile_number"]),
    int(df.iloc[0]["age"]),
    str(df.iloc[0]["gender"]),
    str(df.iloc[0]["region"]),
    str(df.iloc[0]["date_joined"]),
    bool(df.iloc[0]["is_business_user"]),
    int(df.iloc[0]["risk_score"])
)

In [29]:
cursor.execute(insert_query, first_row)

conn.commit()

print("✅ First row inserted successfully!")

✅ First row inserted successfully!

In [30]:
for i in range(5):
    print(i)

0
1
2
3
4

In [31]:
for i in range(5):
    print(df.iloc[i]["customer_id"])

cust100000
cust100001
cust100002
cust100003
cust100004

In [32]:
df.iloc[i]["customer_id"]

'cust100004'

In [33]:
for i in range(5):

    row = (
        str(df.iloc[i]["customer_id"]),
        str(df.iloc[i]["full_name"]),
        str(df.iloc[i]["mobile_number"]),
        int(df.iloc[i]["age"]),
        str(df.iloc[i]["gender"]),
        str(df.iloc[i]["region"]),
        str(df.iloc[i]["date_joined"]),
        bool(df.iloc[i]["is_business_user"]),
        int(df.iloc[i]["risk_score"])
    )

    print(row)

('cust100000', 'Ryan Gallagher', '7631706690', 26, 'female', 'north', '2024-01-28', False, 0)
('cust100001', 'Robert Garza', '806360837', 49, 'female', 'west', '2025-04-16', False, 0)
('cust100002', 'Haley Rhodes', '8124158683', 68, 'male', 'west', '2022-02-10', True, 0)
('cust100003', 'Sonya Mathis', '3662585178', 42, 'male', 'north', '2021-02-18', False, 0)
('cust100004', 'Ryan Wood', '9996228303', 35, 'female', 'south', '2023-04-17', False, 0)

In [35]:
for i in range(5):

    row = (
        str(df.iloc[i]["customer_id"]),
        str(df.iloc[i]["full_name"]),
        str(df.iloc[i]["mobile_number"]),
        int(df.iloc[i]["age"]),
        str(df.iloc[i]["gender"]),
        str(df.iloc[i]["region"]),
        str(df.iloc[i]["date_joined"]),
        bool(df.iloc[i]["is_business_user"]),
        int(df.iloc[i]["risk_score"])
    )
cursor.execute(insert_query, row)

In [37]:
cursor.execute("DELETE FROM customer_master")
conn.commit()

print("Table emptied successfully!")

Table emptied successfully!

In [38]:
cursor.execute("SELECT COUNT(*) FROM customer_master")
print(cursor.fetchone())

(0,)

In [40]:
for i in range(5):

    row = (
        str(df.iloc[i]["customer_id"]),
        str(df.iloc[i]["full_name"]),
        str(df.iloc[i]["mobile_number"]),
        int(df.iloc[i]["age"]),
        str(df.iloc[i]["gender"]),
        str(df.iloc[i]["region"]),
        str(df.iloc[i]["date_joined"]),
        bool(df.iloc[i]["is_business_user"]),
        int(df.iloc[i]["risk_score"])
    )

    cursor.execute(insert_query, row)

conn.commit()

print("✅ First 5 rows inserted successfully!")

✅ First 5 rows inserted successfully!

In [41]:
cursor.execute("SELECT COUNT(*) FROM customer_master")
print(cursor.fetchone())

(5,)

In [42]:
range(5)

range(0, 5)

In [43]:
range(len(df))

range(0, 10000)

In [44]:
cursor.fetchone()

In [49]:
cursor.execute("SELECT COUNT(*) FROM customer_master")
print(cursor.fetchone())

(5,)

In [50]:
cursor.execute("DELETE FROM customer_master")
conn.commit()

print("✅ Table emptied")

✅ Table emptied

In [51]:
cursor.execute("SELECT COUNT(*) FROM customer_master")
print(cursor.fetchone())

(0,)

In [56]:
for i in range(len(df)):

    row = (
        str(df.iloc[i]["customer_id"]),
        str(df.iloc[i]["full_name"]),
        str(df.iloc[i]["mobile_number"]),
        int(df.iloc[i]["age"]),
        str(df.iloc[i]["gender"]),
        str(df.iloc[i]["region"]),
        str(df.iloc[i]["date_joined"]),
        bool(df.iloc[i]["is_business_user"]),
        int(df.iloc[i]["risk_score"])
    )

    cursor.execute(insert_query, row)

conn.commit()

print("🎉 All rows imported successfully!")

IntegrityError: 1062 (23000): Duplicate entry 'cust100000' for key 'customer_master.PRIMARY'

In [57]:
cursor.execute("SELECT COUNT(*) FROM customer_master")
print(cursor.fetchone())

(10000,)

In [58]:
cursor.execute("DELETE FROM customer_master")
conn.commit()

cursor.execute("SELECT COUNT(*) FROM customer_master")
print(cursor.fetchone())

(0,)

In [59]:
print(df["customer_id"].duplicated().sum())

0

In [63]:
for i in range(len(df)):

    row = (
        str(df.iloc[i]["customer_id"]),
        str(df.iloc[i]["full_name"]),
        str(df.iloc[i]["mobile_number"]),
        int(df.iloc[i]["age"]),
        str(df.iloc[i]["gender"]),
        str(df.iloc[i]["region"]),
        str(df.iloc[i]["date_joined"]),
        bool(df.iloc[i]["is_business_user"]),
        int(df.iloc[i]["risk_score"])
    )

    try:
        cursor.execute(insert_query, row)

    except Exception as e:
        print(f"❌ Error at row {i}")
        print(row)
        print(e)
        break

conn.commit()

print("✅ Import finished!")

❌ Error at row 0
('cust100000', 'Ryan Gallagher', '7631706690', 26, 'female', 'north', '2024-01-28', False, 0)
1062 (23000): Duplicate entry 'cust100000' for key 'customer_master.PRIMARY'
✅ Import finished!

In [64]:
cursor.execute("SELECT COUNT(*) FROM customer_master")
print(cursor.fetchone())

(10000,)

In [65]:
merchant_df = pd.read_csv(r"C:\Users\ADMIN\Downloads\4414701-Datasets_-_UPI_Transactions_Data_Analysis\merchant_info.csv")

In [66]:
merchant_df.head()

,merchant_id,merchant_name,merchant_type,region,onboard_date,risk_score
0,merch1000,Anderson Inc,grocery,north,2022-01-14,0.07
1,merch1001,"Rojas, Newton and White",online,north,2021-08-20,0.29
2,merch1002,Knox-Reyes,food,west,2024-10-29,0.20
3,merch1003,"Joseph, Serrano and Gilmore",grocery,north,2023-07-22,0.14
4,merch1004,Brown-Jones,food,north,2024-01-02,0.32

In [67]:
merchant_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   merchant_id    500 non-null    object
 1   merchant_name  500 non-null    object
 2   merchant_type  500 non-null    object
 3   region         500 non-null    object
 4   onboard_date   500 non-null    object
 5   risk_score     500 non-null    float64
dtypes: float64(1), object(5)
memory usage: 23.6+ KB

In [68]:
merchant_df.dtypes

merchant_id       object
merchant_name     object
merchant_type     object
region            object
onboard_date      object
risk_score       float64
dtype: object

In [69]:
insert_merchant_query = """
INSERT INTO merchant_info (
    merchant_id,
    merchant_name,
    category,
    city,
    average_daily_transactions,
    risk_level
)
VALUES (%s, %s, %s, %s, %s, %s)
"""

In [71]:
print(merchant_df.columns.tolist())

['merchant_id', 'merchant_name', 'merchant_type', 'region', 'onboard_date', 'risk_score']

In [72]:
insert_merchant_query = """
INSERT INTO merchant_info (
    merchant_id,
    merchant_name,
    merchant_type,
    region,
    onboard_date,
    risk_score
)
VALUES (%s, %s, %s, %s, %s, %s)
"""

In [73]:
first_row = (
    str(merchant_df.iloc[0]["merchant_id"]),
    str(merchant_df.iloc[0]["merchant_name"]),
    str(merchant_df.iloc[0]["merchant_type"]),
    str(merchant_df.iloc[0]["region"]),
    str(merchant_df.iloc[0]["onboard_date"]),
    int(merchant_df.iloc[0]["risk_score"])
)

cursor.execute(insert_merchant_query, first_row)
conn.commit()

print("✅ First merchant inserted successfully!")

✅ First merchant inserted successfully!

In [74]:
cursor.execute("SELECT COUNT(*) FROM merchant_info")
print(cursor.fetchone())

(1,)

In [75]:
for i in range(len(merchant_df)):

    row = (
        str(merchant_df.iloc[i]["merchant_id"]),
        str(merchant_df.iloc[i]["merchant_name"]),
        str(merchant_df.iloc[i]["merchant_type"]),
        str(merchant_df.iloc[i]["region"]),
        str(merchant_df.iloc[i]["onboard_date"]),
        int(merchant_df.iloc[i]["risk_score"])
    )

    try:
        cursor.execute(insert_merchant_query, row)

    except Exception as e:
        print(f"❌ Error at row {i}")
        print(row)
        print(e)
        break

conn.commit()

print("✅ Merchant table imported successfully!")

❌ Error at row 0
('merch1000', 'Anderson Inc', 'grocery', 'north', '2022-01-14', 0)
1062 (23000): Duplicate entry 'merch1000' for key 'merchant_info.PRIMARY'
✅ Merchant table imported successfully!

In [76]:
cursor.execute("DELETE FROM merchant_info")
conn.commit()

print("✅ merchant_info table emptied")

✅ merchant_info table emptied

In [77]:
cursor.execute("SELECT COUNT(*) FROM merchant_info")
print(cursor.fetchone())

(0,)

In [78]:
for i in range(len(merchant_df)):

    row = (
        str(merchant_df.iloc[i]["merchant_id"]),
        str(merchant_df.iloc[i]["merchant_name"]),
        str(merchant_df.iloc[i]["merchant_type"]),
        str(merchant_df.iloc[i]["region"]),
        str(merchant_df.iloc[i]["onboard_date"]),
        int(merchant_df.iloc[i]["risk_score"])
    )

    try:
        cursor.execute(insert_merchant_query, row)

    except Exception as e:
        print(f"❌ Error at row {i}")
        print(row)
        print(e)
        break

conn.commit()

print("🎉 Merchant table imported successfully!")

❌ Error at row 3
('merch1003', 'Joseph, Serrano and Gilmore', 'grocery', 'north', '2023-07-22', 0)
1406 (22001): Data too long for column 'merchant_name' at row 1
🎉 Merchant table imported successfully!

In [79]:
merchant_df["merchant_name"].str.len().max()

33

In [80]:
merchant_df.loc[
    merchant_df["merchant_name"].str.len().idxmax(),
    "merchant_name"
]

'Leonard, Washington and Rodriguez'

In [81]:
cursor.execute("DELETE FROM merchant_info")
conn.commit()

cursor.execute("SELECT COUNT(*) FROM merchant_info")
print(cursor.fetchone())

(0,)

In [82]:
for i in range(len(merchant_df)):

    row = (
        str(merchant_df.iloc[i]["merchant_id"]),
        str(merchant_df.iloc[i]["merchant_name"]),
        str(merchant_df.iloc[i]["merchant_type"]),
        str(merchant_df.iloc[i]["region"]),
        str(merchant_df.iloc[i]["onboard_date"]),
        int(merchant_df.iloc[i]["risk_score"])
    )

    try:
        cursor.execute(insert_merchant_query, row)

    except Exception as e:
        print(f"❌ Error at row {i}")
        print(row)
        print(e)
        break

conn.commit()

print("🎉 Merchant table imported successfully!")

🎉 Merchant table imported successfully!

In [83]:
cursor.execute("SELECT COUNT(*) FROM merchant_info")
print(cursor.fetchone())

(500,)

In [84]:
print(len(merchant_df))

500

In [85]:
print(len(merchant_df))

500

In [88]:
device_df = pd.read_csv(r"C:\Users\ADMIN\Downloads\4414701-Datasets_-_UPI_Transactions_Data_Analysis\device_info.csv")

In [89]:
device_df.head()

,device_id,customer_id,device_type,app_version,is_rooted,last_active
0,dev100000,cust100000,android,2.5.4,False,2024-10-19 01:24:57.637823
1,dev100001,cust100001,feature_phone,2.6.18,False,2025-07-16 01:53:08.805876
2,dev100002,cust100002,android,2.5.0,False,2024-04-25 05:09:53.162261
3,dev100003,cust100003,android,2.4.12,False,2021-04-24 19:10:51.551382
4,dev100004,cust100004,feature_phone,4.2.0,False,2024-09-15 01:18:05.200875

In [90]:
device_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12000 entries, 0 to 11999
Data columns (total 6 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   device_id    12000 non-null  object
 1   customer_id  12000 non-null  object
 2   device_type  12000 non-null  object
 3   app_version  12000 non-null  object
 4   is_rooted    12000 non-null  bool
 5   last_active  12000 non-null  object
dtypes: bool(1), object(5)
memory usage: 480.6+ KB

In [91]:
device_df.shape

(12000, 6)

In [93]:
device_df.dtypes

device_id      object
customer_id    object
device_type    object
app_version    object
is_rooted        bool
last_active    object
dtype: object

In [105]:
insert_device_query="""
insert into device_info (
    device_id,
    customer_id,
    device_type,
    app_version,
    is_rooted,
    last_active
)
values (%s,%s,%s,%s,%s,%s)
"""

In [106]:
print(device_df.columns.tolist())

['device_id', 'customer_id', 'device_type', 'app_version', 'is_rooted', 'last_active']

In [113]:
first_row = (
    str(device_df.iloc[0]["device_id"]),
    str(device_df.iloc[0]["customer_id"]),
    str(device_df.iloc[0]["device_type"]),
    str(device_df.iloc[0]["app_version"]),
    int(device_df.iloc[0]["is_rooted"]),
    str(device_df.iloc[0]["last_active"])
)

cursor.execute(insert_device_query, first_row)
conn.commit()

print("first device inserted successfully!")

first device inserted successfully!

In [114]:
print(insert_device_query)

insert into device_info (
    device_id,
    customer_id,
    device_type,
    app_version,
    is_rooted,
    last_active
)
values (%s,%s,%s,%s,%s,%s)

In [115]:
device_df.dtypes

device_id      object
customer_id    object
device_type    object
app_version    object
is_rooted        bool
last_active    object
dtype: object

In [116]:
print(type(device_df.iloc[0]["is_rooted"]))
print(device_df.iloc[0]["is_rooted"])

<class 'numpy.bool'>
False

In [117]:
cursor.execute("delete from device_info")
conn.commit()
print("merchant info table emptied")

merchant info table emptied

In [118]:
cursor.execute("select count(*) from device_info")
print(cursor.fetchone())

(0,)

In [123]:
for i in range(len(device_df)):
    row=(
        str(device_df.iloc[0]["device_id"]),
        str(device_df.iloc[0]["customer_id"]),
        str(device_df.iloc[0]["device_type"]),
        str(device_df.iloc[0]["app_version"]),
        int(device_df.iloc[0]["is_rooted"]),
        str(device_df.iloc[0]["last_active"])
    )
    try:
        cursor.execute(insert_device_query,row)
    except Exception as e:
        print(f"error at row{i}")
        print(row)
        print(e)
        break
conn.commit()
print("device table imported successfully")

error at row0
('dev100000', 'cust100000', 'android', '2.5.4', 0, '2024-10-19 01:24:57.637823')
1062 (23000): Duplicate entry 'dev100000' for key 'device_info.PRIMARY'
device table imported successfully

In [124]:
cursor.execute("SELECT COUNT(*) FROM device_info")
print(cursor.fetchone())

(1,)

In [125]:
print(device_df["device_id"].duplicated().sum())

0

In [126]:
cursor.execute("""
SELECT *
FROM device_info
WHERE device_id = %s
""", (device_df.iloc[0]["device_id"],))

print(cursor.fetchall())

[('dev100000', 'cust100000', 'android', '2.5.4', 0, datetime.datetime(2024, 10, 19, 1, 24, 58))]

In [127]:
duplicates = device_df[device_df["device_id"].duplicated(keep=False)]
duplicates

Empty DataFrame
Columns: [device_id, customer_id, device_type, app_version, is_rooted, last_active]
Index: []

In [128]:
print(duplicates)

Empty DataFrame
Columns: [device_id, customer_id, device_type, app_version, is_rooted, last_active]
Index: []

In [129]:
print("Rows:", len(device_df))

Rows: 12000

In [130]:
print("Duplicate device_id:", device_df["device_id"].duplicated().sum())

Duplicate device_id: 0

In [131]:
print(device_df[device_df["device_id"].duplicated(keep=False)])

Empty DataFrame
Columns: [device_id, customer_id, device_type, app_version, is_rooted, last_active]
Index: []

In [132]:
cursor.execute("SELECT COUNT(*) FROM device_info")
print(cursor.fetchone())

(1,)

In [133]:
cursor.execute("SELECT COUNT(*) FROM device_info")
print(cursor.fetchone())

(1,)

In [134]:
cursor.execute("SELECT * FROM device_info")
print(cursor.fetchall())

[('dev100000', 'cust100000', 'android', '2.5.4', 0, datetime.datetime(2024, 10, 19, 1, 24, 58))]

In [135]:
cursor.execute("DELETE FROM device_info")
conn.commit()

cursor.execute("SELECT COUNT(*) FROM device_info")
print(cursor.fetchone())

(0,)

In [136]:
cursor.execute("SELECT COUNT(*) FROM device_info")
print(cursor.fetchone())

(0,)

In [137]:
for i in range(len(device_df)):

    row = (
        str(device_df.iloc[i]["device_id"]),
        str(device_df.iloc[i]["customer_id"]),
        str(device_df.iloc[i]["device_type"]),
        str(device_df.iloc[i]["app_version"]),
        int(device_df.iloc[i]["is_rooted"]),
        str(device_df.iloc[i]["last_active"])
    )

    try:
        cursor.execute(insert_device_query, row)

    except Exception as e:
        print(f"❌ Error at row {i}")
        print(row)
        print(e)
        break

conn.commit()

print("🎉 Device table imported successfully!")

🎉 Device table imported successfully!

In [138]:
cursor.execute("SELECT COUNT(*) FROM device_info")
print(cursor.fetchone())

(12000,)

In [139]:
print(len(device_df))

12000

In [140]:
upi_account_df = pd.read_csv(r"C:\Users\ADMIN\Downloads\4414701-Datasets_-_UPI_Transactions_Data_Analysis\upi_account_details.csv")

In [141]:
upi_account_df.head()

,upi_id,customer_id,bank_name,account_type,date_added,status
0,elizabeth4408@upi,cust106759,sbi,current,2022-02-22,active
1,daniel5127@upi,cust104765,hdfc,savings,2022-04-02,active
2,heidi2675@upi,cust102710,axis,savings,2023-12-19,active
3,dr.3519@upi,cust107076,axis,credit_card_linked,2025-01-23,active
4,jeremy9552@upi,cust102202,sbi,current,2025-07-18,active

In [143]:
upi_account_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12000 entries, 0 to 11999
Data columns (total 6 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   upi_id        12000 non-null  object
 1   customer_id   12000 non-null  object
 2   bank_name     12000 non-null  object
 3   account_type  12000 non-null  object
 4   date_added    12000 non-null  object
 5   status        12000 non-null  object
dtypes: object(6)
memory usage: 562.6+ KB

In [144]:
upi_account_df.shape

(12000, 6)

In [146]:
upi_account_df.dtypes

upi_id          object
customer_id     object
bank_name       object
account_type    object
date_added      object
status          object
dtype: object

In [147]:
insert_upi_account_query = """
INSERT INTO upi_account_details (
    upi_id,
    customer_id,
    bank_name,
    account_type,
    date_added,
    status
)
VALUES (%s, %s, %s, %s, %s, %s)
"""

In [150]:
for i in range(len(upi_account_df)):

    row = (
        str(upi_account_df.iloc[i]["upi_id"]),
        str(upi_account_df.iloc[i]["customer_id"]),
        str(upi_account_df.iloc[i]["bank_name"]),
        str(upi_account_df.iloc[i]["account_type"]),
        str(upi_account_df.iloc[i]["date_added"]),
        str(upi_account_df.iloc[i]["status"])
    )

    try:
        cursor.execute(insert_upi_account_query, row)

    except Exception as e:
        print(f"❌ Error at row {i}")
        print(row)
        print(e)
        break

conn.commit()

print("🎉 UPI account table imported successfully!")

🎉 UPI account table imported successfully!

In [152]:
cursor.execute("SELECT COUNT(*) FROM upi_account_details")
print(cursor.fetchone())

(12000,)

In [153]:
print(len(upi_account_df))

12000

In [166]:
upi_history_df = pd.read_csv(r"C:\Users\ADMIN\Downloads\4414701-Datasets_-_UPI_Transactions_Data_Analysis\upi_transaction_history.csv")

In [167]:
upi_history_df.head()

,transaction_id,upi_id,customer_id,timestamp,amount,transaction_type,merchant_id,counterparty_upi,status,device_id,device_type,channel,fraud_flag,reversal_flag,failure_reason
0,txn10000000,marisa9078@upi,cust101488,2025-06-04 21:36:19.632258,9.88,send,NaN,user6545@upi,success,dev101488,feature_phone,app,False,False,NaN
1,txn10000001,michelle5950@upi,cust107876,2025-05-22 04:26:44.200117,76.25,receive,NaN,user3199@upi,success,dev107876,ios,app,False,False,NaN
2,txn10000002,jeffery4732@upi,cust100901,2025-08-02 02:34:14.690327,26.44,merchant_payment,merch1113,user4690@upi,success,dev100901,android,intent,False,False,NaN
3,txn10000003,troy1833@upi,cust105890,2025-01-30 03:53:31.110447,84.43,send,NaN,user1982@upi,success,dev105890,tablet,qr_code,False,False,NaN
4,txn10000004,tammy4986@upi,cust106780,2025-07-05 21:36:52.813878,10.33,receive,NaN,user4914@upi,success,dev106780,tablet,qr_code,False,False,NaN

In [168]:
upi_history_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100000 entries, 0 to 99999
Data columns (total 15 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   transaction_id    100000 non-null  object
 1   upi_id            100000 non-null  object
 2   customer_id       100000 non-null  object
 3   timestamp         100000 non-null  object
 4   amount            100000 non-null  float64
 5   transaction_type  100000 non-null  object
 6   merchant_id       30149 non-null   object
 7   counterparty_upi  100000 non-null  object
 8   status            100000 non-null  object
 9   device_id         100000 non-null  object
 10  device_type       100000 non-null  object
 11  channel           100000 non-null  object
 12  fraud_flag        100000 non-null  bool
 13  reversal_flag     100000 non-null  bool
 14  failure_reason    5871 non-null    object
dtypes: bool(2), float64(1), object(12)
memory usage: 10.1+ MB

In [169]:
upi_history_df.shape

(100000, 15)

In [170]:
upi_history_df.dtypes

transaction_id       object
upi_id               object
customer_id          object
timestamp            object
amount              float64
transaction_type     object
merchant_id          object
counterparty_upi     object
status               object
device_id            object
device_type          object
channel              object
fraud_flag             bool
reversal_flag          bool
failure_reason       object
dtype: object

In [179]:
insert_upi_history_query = """
INSERT INTO upi_transaction_history (
    transaction_id,
    upi_id,
    customer_id,
    timestamp,
    amount,
    transaction_type,
    merchant_id,
    counterparty_upi,
    status,
    device_id,
    device_type,
    channel,
    fraud_flag,
    reversal_flag,
    failure_reason
)
VALUES (%s, %s, %s, %s, %s, %s,%s,%s,%s,%s,%s,%s,%s,%s,%s)
"""

In [182]:
failure_reason = None if pd.isna(upi_history_df.iloc[i]["failure_reason"]) else str(upi_history_df.iloc[i]["failure_reason"])

In [183]:
merchant_id = None if pd.isna(upi_history_df.iloc[i]["merchant_id"]) else str(upi_history_df.iloc[i]["merchant_id"])

In [189]:
for i in range(len(upi_history_df)):
    merchant_id = None if pd.isna(upi_history_df.iloc[i]["merchant_id"]) else str(upi_history_df.iloc[i]["merchant_id"])
    failure_reason = None if pd.isna(upi_history_df.iloc[i]["failure_reason"]) else str(upi_history_df.iloc[i]["failure_reason"])

    row = (
        str(upi_history_df.iloc[i]["transaction_id"]),
        str(upi_history_df.iloc[i]["upi_id"]),
        str(upi_history_df.iloc[i]["customer_id"]),
        str(upi_history_df.iloc[i]["timestamp"]),
        str(upi_history_df.iloc[i]["amount"]),
        str(upi_history_df.iloc[i]["transaction_type"]),
        merchant_id,
        str(upi_history_df.iloc[i]["counterparty_upi"]),
        str(upi_history_df.iloc[i]["status"]),
        str(upi_history_df.iloc[i]["device_id"]),
        str(upi_history_df.iloc[i]["device_type"]),
        str(upi_history_df.iloc[i]["channel"]),
        int(upi_history_df.iloc[i]["fraud_flag"]),
        int(upi_history_df.iloc[i]["reversal_flag"]),
        failure_reason
    )
    if i == 0:
        print(row)
    try:
        cursor.execute(insert_upi_history_query, row)

    except Exception as e:
        print(f"❌ Error at row {i}")
        print(row)
        print(e)
        break

conn.commit()

print("🎉 UPI history table imported successfully!")

('txn10000000', 'marisa9078@upi', 'cust101488', '2025-06-04 21:36:19.632258', '9.88', 'send', None, 'user6545@upi', 'success', 'dev101488', 'feature_phone', 'app', 0, 0, None)
❌ Error at row 6
('txn10000006', 'stephanie3115@upi', 'cust108896', '2024-07-30 03:10:27.963203', '77.74', 'send', None, 'user3421@upi', 'failed', 'dev108896', 'feature_phone', 'app', 0, 1, 'incorrect_pin')
3819 (HY000): Check constraint 'upi_transaction_history_chk_2' is violated.
🎉 UPI history table imported successfully!

In [190]:
print(upi_history_df["status"].unique())

['success' 'failed' 'pending']

In [191]:
print(upi_history_df["status"].value_counts())

status
success    92140
failed      5871
pending     1989
Name: count, dtype: int64

In [192]:
for i in range(len(upi_history_df)):
    merchant_id = None if pd.isna(upi_history_df.iloc[i]["merchant_id"]) else str(upi_history_df.iloc[i]["merchant_id"])
    failure_reason = None if pd.isna(upi_history_df.iloc[i]["failure_reason"]) else str(upi_history_df.iloc[i]["failure_reason"])

    row = (
        str(upi_history_df.iloc[i]["transaction_id"]),
        str(upi_history_df.iloc[i]["upi_id"]),
        str(upi_history_df.iloc[i]["customer_id"]),
        str(upi_history_df.iloc[i]["timestamp"]),
        str(upi_history_df.iloc[i]["amount"]),
        str(upi_history_df.iloc[i]["transaction_type"]),
        merchant_id,
        str(upi_history_df.iloc[i]["counterparty_upi"]),
        str(upi_history_df.iloc[i]["status"]),
        str(upi_history_df.iloc[i]["device_id"]),
        str(upi_history_df.iloc[i]["device_type"]),
        str(upi_history_df.iloc[i]["channel"]),
        int(upi_history_df.iloc[i]["fraud_flag"]),
        int(upi_history_df.iloc[i]["reversal_flag"]),
        failure_reason
    )
    if i == 0:
        print(row)
    try:
        cursor.execute(insert_upi_history_query, row)

    except Exception as e:
        print(f"❌ Error at row {i}")
        print(row)
        print(e)
        break

conn.commit()

print("🎉 UPI history table imported successfully!")

('txn10000000', 'marisa9078@upi', 'cust101488', '2025-06-04 21:36:19.632258', '9.88', 'send', None, 'user6545@upi', 'success', 'dev101488', 'feature_phone', 'app', 0, 0, None)
❌ Error at row 12
('txn10000012', 'adam2499@upi', 'cust108255', '2023-02-07 20:03:33.344593', '17.88', 'bill_pay', 'merch1488', 'user3042@upi', 'success', 'dev108255', 'tablet', 'qr_code', 0, 0, None)
3819 (HY000): Check constraint 'upi_transaction_history_chk_1' is violated.
🎉 UPI history table imported successfully!

In [193]:
print(upi_history_df["transaction_type"].value_counts())

transaction_type
send                35032
receive             34819
merchant_payment    25097
bill_pay             5052
Name: count, dtype: int64

In [194]:
for i in range(len(upi_history_df)):
    merchant_id = None if pd.isna(upi_history_df.iloc[i]["merchant_id"]) else str(upi_history_df.iloc[i]["merchant_id"])
    failure_reason = None if pd.isna(upi_history_df.iloc[i]["failure_reason"]) else str(upi_history_df.iloc[i]["failure_reason"])

    row = (
        str(upi_history_df.iloc[i]["transaction_id"]),
        str(upi_history_df.iloc[i]["upi_id"]),
        str(upi_history_df.iloc[i]["customer_id"]),
        str(upi_history_df.iloc[i]["timestamp"]),
        str(upi_history_df.iloc[i]["amount"]),
        str(upi_history_df.iloc[i]["transaction_type"]),
        merchant_id,
        str(upi_history_df.iloc[i]["counterparty_upi"]),
        str(upi_history_df.iloc[i]["status"]),
        str(upi_history_df.iloc[i]["device_id"]),
        str(upi_history_df.iloc[i]["device_type"]),
        str(upi_history_df.iloc[i]["channel"]),
        int(upi_history_df.iloc[i]["fraud_flag"]),
        int(upi_history_df.iloc[i]["reversal_flag"]),
        failure_reason
    )
    if i == 0:
        print(row)
    try:
        cursor.execute(insert_upi_history_query, row)

    except Exception as e:
        print(f"❌ Error at row {i}")
        print(row)
        print(e)
        break

conn.commit()

print("🎉 UPI history table imported successfully!")

('txn10000000', 'marisa9078@upi', 'cust101488', '2025-06-04 21:36:19.632258', '9.88', 'send', None, 'user6545@upi', 'success', 'dev101488', 'feature_phone', 'app', 0, 0, None)
🎉 UPI history table imported successfully!

In [ ]:
for i in range(len(upi_history_df)):
    merchant_id = None if pd.isna(upi_history_df.iloc[i]["merchant_id"]) else str(upi_history_df.iloc[i]["merchant_id"])
    failure_reason = None if pd.isna(upi_history_df.iloc[i]["failure_reason"]) else str(upi_history_df.iloc[i]["failure_reason"])

    row = (
        str(upi_history_df.iloc[i]["transaction_id"]),
        str(upi_history_df.iloc[i]["upi_id"]),
        str(upi_history_df.iloc[i]["customer_id"]),
        str(upi_history_df.iloc[i]["timestamp"]),
        str(upi_history_df.iloc[i]["amount"]),
        str(upi_history_df.iloc[i]["transaction_type"]),
        merchant_id,
        str(upi_history_df.iloc[i]["counterparty_upi"]),
        str(upi_history_df.iloc[i]["status"]),
        str(upi_history_df.iloc[i]["device_id"]),
        str(upi_history_df.iloc[i]["device_type"]),
        str(upi_history_df.iloc[i]["channel"]),
        int(upi_history_df.iloc[i]["fraud_flag"]),
        int(upi_history_df.iloc[i]["reversal_flag"]),
        failure_reason
    )
    if i == 0:
        print(row)
    try:
        cursor.execute(insert_upi_history_query, row)

    except Exception as e:
        print(f"❌ Error at row {i}")
        print(row)
        print(e)
        break

conn.commit()

print("🎉 UPI history table imported successfully!")

('txn10000000', 'marisa9078@upi', 'cust101488', '2025-06-04 21:36:19.632258', '9.88', 'send', None, 'user6545@upi', 'success', 'dev101488', 'feature_phone', 'app', 0, 0, None)

In [195]:
for i in range(len(upi_history_df)):
    merchant_id = None if pd.isna(upi_history_df.iloc[i]["merchant_id"]) else str(upi_history_df.iloc[i]["merchant_id"])
    failure_reason = None if pd.isna(upi_history_df.iloc[i]["failure_reason"]) else str(upi_history_df.iloc[i]["failure_reason"])

    row = (
        str(upi_history_df.iloc[i]["transaction_id"]),
        str(upi_history_df.iloc[i]["upi_id"]),
        str(upi_history_df.iloc[i]["customer_id"]),
        str(upi_history_df.iloc[i]["timestamp"]),
        str(upi_history_df.iloc[i]["amount"]),
        str(upi_history_df.iloc[i]["transaction_type"]),
        merchant_id,
        str(upi_history_df.iloc[i]["counterparty_upi"]),
        str(upi_history_df.iloc[i]["status"]),
        str(upi_history_df.iloc[i]["device_id"]),
        str(upi_history_df.iloc[i]["device_type"]),
        str(upi_history_df.iloc[i]["channel"]),
        int(upi_history_df.iloc[i]["fraud_flag"]),
        int(upi_history_df.iloc[i]["reversal_flag"]),
        failure_reason
    )
    try:
        cursor.execute(insert_upi_history_query, row)

    except Exception as e:
        print(f"❌ Error at row {i}")
        print(row)
        print(e)
        break

conn.commit()

print("🎉 UPI history table imported successfully!")

❌ Error at row 0
('txn10000000', 'marisa9078@upi', 'cust101488', '2025-06-04 21:36:19.632258', '9.88', 'send', None, 'user6545@upi', 'success', 'dev101488', 'feature_phone', 'app', 0, 0, None)
1062 (23000): Duplicate entry 'txn10000000' for key 'upi_transaction_history.PRIMARY'
🎉 UPI history table imported successfully!

In [197]:
for i in range(len(upi_history_df)):

    merchant_id = None if pd.isna(upi_history_df.iloc[i]["merchant_id"]) else str(upi_history_df.iloc[i]["merchant_id"])
    failure_reason = None if pd.isna(upi_history_df.iloc[i]["failure_reason"]) else str(upi_history_df.iloc[i]["failure_reason"])

    row = (
        str(upi_history_df.iloc[i]["transaction_id"]),
        str(upi_history_df.iloc[i]["upi_id"]),
        str(upi_history_df.iloc[i]["customer_id"]),
        str(upi_history_df.iloc[i]["timestamp"]),
        float(upi_history_df.iloc[i]["amount"]),
        str(upi_history_df.iloc[i]["transaction_type"]),
        merchant_id,
        str(upi_history_df.iloc[i]["counterparty_upi"]),
        str(upi_history_df.iloc[i]["status"]),
        str(upi_history_df.iloc[i]["device_id"]),
        str(upi_history_df.iloc[i]["device_type"]),
        str(upi_history_df.iloc[i]["channel"]),
        int(upi_history_df.iloc[i]["fraud_flag"]),
        int(upi_history_df.iloc[i]["reversal_flag"]),
        failure_reason
    )

    try:
        cursor.execute(insert_upi_history_query, row)

    except Exception as e:
        print(f"❌ Error at row {i}")
        print(row)
        print(e)
        break

conn.commit()

if success:
    print("🎉 UPI Transaction History imported successfully!")
else:
    print("❌ Import stopped because of the above error.")

❌ Error at row 0
('txn10000000', 'marisa9078@upi', 'cust101488', '2025-06-04 21:36:19.632258', 9.88, 'send', None, 'user6545@upi', 'success', 'dev101488', 'feature_phone', 'app', 0, 0, None)
1062 (23000): Duplicate entry 'txn10000000' for key 'upi_transaction_history.PRIMARY'

NameError: name 'success' is not defined

In [199]:
feedback_df = pd.read_csv(r"C:\Users\ADMIN\Downloads\4414701-Datasets_-_UPI_Transactions_Data_Analysis\customer_feedback_surveys.csv")

In [200]:
feedback_df.head()

,feedback_id,customer_id,date_submitted,feedback_text,satisfaction_score,issue_type,resolved
0,fdbk100000,cust106029,2021-08-14,Weight what decision able gun shoulder.,4,fraud,True
1,fdbk100001,cust101758,2025-03-30,Case discuss approach leave hair.,3,transaction,False
2,fdbk100002,cust107269,2025-07-24,Idea as effect bed need shake.,4,app_usability,False
3,fdbk100003,cust108175,2024-06-07,Image design soldier strategy character learn ...,4,app_usability,False
4,fdbk100004,cust101420,2022-01-12,Two lose traditional approach commercial throw...,3,transaction,True

In [201]:
feedback_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4000 entries, 0 to 3999
Data columns (total 7 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   feedback_id         4000 non-null   object
 1   customer_id         4000 non-null   object
 2   date_submitted      4000 non-null   object
 3   feedback_text       4000 non-null   object
 4   satisfaction_score  4000 non-null   int64
 5   issue_type          4000 non-null   object
 6   resolved            4000 non-null   bool
dtypes: bool(1), int64(1), object(5)
memory usage: 191.5+ KB

In [202]:
feedback_df.shape

(4000, 7)

In [203]:
feedback_df.columns

Index(['feedback_id', 'customer_id', 'date_submitted', 'feedback_text',
       'satisfaction_score', 'issue_type', 'resolved'],
      dtype='object')

In [206]:
insert_feedback_query = """
INSERT INTO customer_feedback_surveys (
    feedback_id,
    customer_id,
    date_submitted,
    feedback_text,
    satisfaction_score,
    issue_type,
    resolved
)
VALUES (%s, %s, %s, %s, %s, %s,%s)
"""

In [209]:
for i in range(len(feedback_df)):

    row = (
        str(feedback_df.iloc[i]["feedback_id"]),
        str(feedback_df.iloc[i]["customer_id"]),
        str(feedback_df.iloc[i]["date_submitted"]),
        str(feedback_df.iloc[i]["feedback_text"]),
        str(feedback_df.iloc[i]["satisfaction_score"]),
        str(feedback_df.iloc[i]["issue_type"]),
        str(feedback_df.iloc[i]["resolved"])
    )

    try:
        cursor.execute(insert_feedback_query, row)

    except Exception as e:
        print(f"❌ Error at row {i}")
        print(row)
        print(e)
        break

conn.commit()

print("🎉 feedback table imported successfully!")

❌ Error at row 0
('fdbk100000', 'cust106029', '2021-08-14', 'Weight what decision able gun shoulder.', '4', 'fraud', 'True')
1062 (23000): Duplicate entry 'fdbk100000' for key 'customer_feedback_surveys.PRIMARY'
🎉 feedback table imported successfully!

In [210]:
feedback_df.head()

,feedback_id,customer_id,date_submitted,feedback_text,satisfaction_score,issue_type,resolved
0,fdbk100000,cust106029,2021-08-14,Weight what decision able gun shoulder.,4,fraud,True
1,fdbk100001,cust101758,2025-03-30,Case discuss approach leave hair.,3,transaction,False
2,fdbk100002,cust107269,2025-07-24,Idea as effect bed need shake.,4,app_usability,False
3,fdbk100003,cust108175,2024-06-07,Image design soldier strategy character learn ...,4,app_usability,False
4,fdbk100004,cust101420,2022-01-12,Two lose traditional approach commercial throw...,3,transaction,True

In [211]:
len(feedback_df)

4000

In [212]:
insert_feedback_query = """
INSERT INTO customer_feedback_surveys (
    feedback_id,
    customer_id,
    date_submitted,
    feedback_text,
    satisfaction_score,
    issue_type,
    resolved
)
VALUES (%s, %s, %s, %s, %s, %s, %s)
"""

In [213]:
for i in range(len(feedback_df)):

    row = (
        str(feedback_df.iloc[i]["feedback_id"]),
        str(feedback_df.iloc[i]["customer_id"]),
        str(feedback_df.iloc[i]["date_submitted"]),
        str(feedback_df.iloc[i]["feedback_text"]),
        str(feedback_df.iloc[i]["satisfaction_score"]),
        str(feedback_df.iloc[i]["issue_type"]),
        str(feedback_df.iloc[i]["resolved"])
    )

    cursor.execute(insert_feedback_query, row)

conn.commit()

print("🎉 Customer feedback data imported successfully!")

🎉 Customer feedback data imported successfully!

In [214]:
fraud_df = pd.read_csv(r"C:\Users\ADMIN\Downloads\4414701-Datasets_-_UPI_Transactions_Data_Analysis\fraud_alert_history.csv")

In [215]:
fraud_df.head()

,alert_id,transaction_id,alert_type,alert_date,resolved,resolution_date,remarks
0,alert134117,txn10034117,frequent_failure,2025-08-03 13:29:58.950559,False,NaN,Strategy forward the risk necessary company re...
1,alert183925,txn10083925,frequent_failure,2024-10-09 09:41:15.203880,True,2024-10-11 02:41:15.203880,Art do federal short.
2,alert163439,txn10063439,unusual_time,2025-02-23 01:23:55.939700,True,2025-02-24 10:23:55.939700,Age board fine participant join.
3,alert164967,txn10064967,frequent_failure,2025-07-08 21:50:16.926780,True,2025-07-09 19:50:16.926780,Among doctor much physical interest catch.
4,alert159661,txn10059661,frequent_failure,2025-08-02 22:59:36.158113,True,2025-08-05 07:59:36.158113,Would catch themselves be represent why decade.

In [216]:
fraud_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2000 entries, 0 to 1999
Data columns (total 7 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   alert_id         2000 non-null   object
 1   transaction_id   2000 non-null   object
 2   alert_type       2000 non-null   object
 3   alert_date       2000 non-null   object
 4   resolved         2000 non-null   bool
 5   resolution_date  1752 non-null   object
 6   remarks          2000 non-null   object
dtypes: bool(1), object(6)
memory usage: 95.8+ KB

In [217]:
fraud_df.shape

(2000, 7)

In [222]:
insert_fraud_query = """
INSERT INTO fraud_alert_history (
    alert_id,
    transaction_id,
    alert_type,
    alert_date,
    resolved,
    resolution_date,
    remarks
)
VALUES (%s, %s, %s, %s, %s, %s, %s)
"""

In [224]:
for i in range(len(fraud_df)):

    row = (
        str(fraud_df.iloc[i]["alert_id"]),
        str(fraud_df.iloc[i]["transaction_id"]),
        str(fraud_df.iloc[i]["alert_type"]),
        str(fraud_df.iloc[i]["alert_date"]),
        str(fraud_df.iloc[i]["resolved"]),
        str(fraud_df.iloc[i]["resolution_date"]),
        str(fraud_df.iloc[i]["remarks"])
    )

    cursor.execute(insert_fraud_query, row)

conn.commit()

print("🎉 fraud table data imported successfully!")

OperationalError: 2013 (HY000): Lost connection to MySQL server during query

In [221]:
len(fraud_df)

2000

In [225]:
fraud_df = pd.read_csv("fraud_alert_history.csv")

FileNotFoundError: [Errno 2] No such file or directory: 'fraud_alert_history.csv'

In [226]:
fraud_df = pd.read_csv(r"C:\Users\ADMIN\Downloads\4414701-Datasets_-_UPI_Transactions_Data_Analysis\fraud_alert_history.csv")

In [227]:
fraud_df.head()

,alert_id,transaction_id,alert_type,alert_date,resolved,resolution_date,remarks
0,alert134117,txn10034117,frequent_failure,03-08-2025 13:29:59,False,NaN,Strategy forward the risk necessary company re...
1,alert183925,txn10083925,frequent_failure,09-10-2024 09:41:15,True,41:15.2,Art do federal short.
2,alert163439,txn10063439,unusual_time,23-02-2025 01:23:56,True,23:55.9,Age board fine participant join.
3,alert164967,txn10064967,frequent_failure,08-07-2025 21:50:17,True,50:16.9,Among doctor much physical interest catch.
4,alert159661,txn10059661,frequent_failure,02-08-2025 22:59:36,True,59:36.2,Would catch themselves be represent why decade.

In [228]:
fraud_df.describe()

,alert_id,transaction_id,alert_type,alert_date,resolved,resolution_date,remarks
count,2000,2000,2000,2000,2000,1752,2000
unique,2000,2000,4,1998,2,1666,2000
top,alert134117,txn10034117,unusual_time,06-08-2025 08:06:42,True,06:42.1,Strategy forward the risk necessary company re...
freq,1,1,507,2,1752,24,1

In [229]:
fraud_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2000 entries, 0 to 1999
Data columns (total 7 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   alert_id         2000 non-null   object
 1   transaction_id   2000 non-null   object
 2   alert_type       2000 non-null   object
 3   alert_date       2000 non-null   object
 4   resolved         2000 non-null   bool
 5   resolution_date  1752 non-null   object
 6   remarks          2000 non-null   object
dtypes: bool(1), object(6)
memory usage: 95.8+ KB

In [230]:
fraud_df.shape

(2000, 7)

In [231]:
insert_fraud_query = """
INSERT INTO fraud_alert_history (
    alert_id,
    transaction_id,
    alert_type,
    alert_date,
    resolved,
    resolution_date,
    remarks
)
VALUES (%s, %s, %s, %s, %s, %s, %s)
"""

In [232]:
for i in range(len(fraud_df)):

    row = (
        str(fraud_df.iloc[i]["alert_id"]),
        str(fraud_df.iloc[i]["transaction_id"]),
        str(fraud_df.iloc[i]["alert_type"]),
        str(fraud_df.iloc[i]["alert_date"]),
        str(fraud_df.iloc[i]["resolved"]),
        str(fraud_df.iloc[i]["resolution_date"]),
        str(fraud_df.iloc[i]["remarks"])
    )

    cursor.execute(insert_fraud_query, row)

conn.commit()

print("🎉 fraud table data imported successfully!")

OperationalError: 2013 (HY000): Lost connection to MySQL server during query

In [233]:
for i in range(len(fraud_df)):

    row = (
        str(fraud_df.iloc[i]["alert_id"]),
        str(fraud_df.iloc[i]["transaction_id"]),
        str(fraud_df.iloc[i]["alert_type"]),
        str(fraud_df.iloc[i]["alert_date"]),
        str(fraud_df.iloc[i]["resolved"]),
        str(fraud_df.iloc[i]["resolution_date"]),
        str(fraud_df.iloc[i]["remarks"])
    )

    print(f"Inserting row {i}")

    cursor.execute(insert_fraud_query, row)

conn.commit()

Inserting row 0

OperationalError: 2013 (HY000): Lost connection to MySQL server during query

In [234]:
print(conn.is_connected())

False

In [235]:
print(fraud_df[["alert_date", "resolution_date"]].head(10))

            alert_date resolution_date
0  03-08-2025 13:29:59             NaN
1  09-10-2024 09:41:15         41:15.2
2  23-02-2025 01:23:56         23:55.9
3  08-07-2025 21:50:17         50:16.9
4  02-08-2025 22:59:36         59:36.2
5  05-03-2025 13:01:59         01:59.4
6  03-08-2025 22:53:06         06:42.0
7  18-12-2021 21:00:55         00:55.2
8  08-06-2025 02:15:11             NaN
9  09-07-2025 03:05:02             NaN

In [236]:
row = (
    str(fraud_df.iloc[0]["alert_id"]),
    str(fraud_df.iloc[0]["transaction_id"]),
    str(fraud_df.iloc[0]["alert_type"]),
    str(fraud_df.iloc[0]["alert_date"]),
    str(fraud_df.iloc[0]["resolved"]),
    str(fraud_df.iloc[0]["resolution_date"]),
    str(fraud_df.iloc[0]["remarks"])
)

cursor.execute(insert_fraud_query, row)
conn.commit()

print("Inserted first row successfully!")

OperationalError: 2013 (HY000): Lost connection to MySQL server during query

In [237]:
fraud_df.iloc[0]

alert_id                                                 alert134117
transaction_id                                           txn10034117
alert_type                                          frequent_failure
alert_date                                       03-08-2025 13:29:59
resolved                                                       False
resolution_date                                                  NaN
remarks            Strategy forward the risk necessary company re...
Name: 0, dtype: object

In [239]:
import mysql.connector

conn = mysql.connector.connect(
    host="localhost",
    user="root",
    password="Shreyassneha@1303",
    database="upi_transaction_analysis"
)

cursor = conn.cursor()

print(conn.is_connected())

True

In [240]:
fraud_df["alert_date"] = pd.to_datetime(
    fraud_df["alert_date"],
    format="%d-%m-%Y %H:%M:%S"
).dt.date

In [241]:
fraud_df["resolution_date"] = pd.to_datetime(
    fraud_df["resolution_date"],
    errors="coerce"
)

C:\Users\ADMIN\AppData\Local\Temp\ipykernel_4104\3274096884.py:1: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  fraud_df["resolution_date"] = pd.to_datetime(

In [242]:
fraud_df["resolution_date"].head(10)

0                   NaT
1                   NaT
2   2026-07-26 23:55:54
3                   NaT
4                   NaT
5   2026-07-26 01:59:24
6   2026-07-26 06:42:00
7   2026-07-26 00:55:12
8                   NaT
9                   NaT
Name: resolution_date, dtype: datetime64[ns]

In [243]:
fraud_df["resolution_date"].unique()[:10]

<DatetimeArray>
[                'NaT', '2026-07-26 23:55:54', '2026-07-26 01:59:24',
 '2026-07-26 06:42:00', '2026-07-26 00:55:12', '2026-07-26 07:29:48',
 '2026-07-26 16:19:42', '2026-07-26 04:17:48', '2026-07-26 10:06:36',
 '2026-07-26 21:06:18']
Length: 10, dtype: datetime64[ns]

In [244]:
fraud_df["alert_date"].head()

0    2025-08-03
1    2024-10-09
2    2025-02-23
3    2025-07-08
4    2025-08-02
Name: alert_date, dtype: object

In [245]:
fraud_df["alert_date"].dtype

dtype('O')

In [246]:
print(row)

('alert134117', 'txn10034117', 'frequent_failure', '03-08-2025 13:29:59', 'False', 'nan', 'Strategy forward the risk necessary company ready.')

In [247]:
cursor.execute(insert_fraud_query, row)

DataError: 1292 (22007): Incorrect date value: '03-08-2025 13:29:59' for column 'alert_date' at row 1

In [248]:
row = (
    fraud_df.iloc[0]["alert_id"],
    fraud_df.iloc[0]["transaction_id"],
    fraud_df.iloc[0]["alert_type"],
    fraud_df.iloc[0]["alert_date"],
    bool(fraud_df.iloc[0]["resolved"]),
    None if pd.isna(fraud_df.iloc[0]["resolution_date"]) else fraud_df.iloc[0]["resolution_date"],
    fraud_df.iloc[0]["remarks"]
)

print(row)

try:
    cursor.execute(insert_fraud_query, row)
    conn.commit()
    print("✅ First row inserted successfully!")

except Exception as e:
    print("❌ Error:")
    print(e)

('alert134117', 'txn10034117', 'frequent_failure', datetime.date(2025, 8, 3), False, None, 'Strategy forward the risk necessary company ready.')
✅ First row inserted successfully!

In [249]:
for i in range(len(fraud_df)):

    row = (
        fraud_df.iloc[i]["alert_id"],
        fraud_df.iloc[i]["transaction_id"],
        fraud_df.iloc[i]["alert_type"],
        fraud_df.iloc[i]["alert_date"],
        bool(fraud_df.iloc[i]["resolved"]),
        None if pd.isna(fraud_df.iloc[i]["resolution_date"]) else fraud_df.iloc[i]["resolution_date"],
        fraud_df.iloc[i]["remarks"]
    )

    cursor.execute(insert_fraud_query, row)

conn.commit()

print("🎉 Fraud Alert History table imported successfully!")

IntegrityError: 1062 (23000): Duplicate entry 'alert134117' for key 'fraud_alert_history.PRIMARY'

In [260]:
fraud_new_df = pd.read_csv(r"C:\Users\ADMIN\Downloads\4414701-Datasets_-_UPI_Transactions_Data_Analysis\fraud_alert_history.csv")

In [261]:
fraud_new_df.head()

,alert_id,transaction_id,alert_type,alert_date,resolved,resolution_date,remarks
0,alert134117,txn10034117,frequent_failure,03-08-2025 13:29:59,False,NaN,Strategy forward the risk necessary company re...
1,alert183925,txn10083925,frequent_failure,09-10-2024 09:41:15,True,41:15.2,Art do federal short.
2,alert163439,txn10063439,unusual_time,23-02-2025 01:23:56,True,23:55.9,Age board fine participant join.
3,alert164967,txn10064967,frequent_failure,08-07-2025 21:50:17,True,50:16.9,Among doctor much physical interest catch.
4,alert159661,txn10059661,frequent_failure,02-08-2025 22:59:36,True,59:36.2,Would catch themselves be represent why decade.

In [262]:
fraud_new_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2000 entries, 0 to 1999
Data columns (total 7 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   alert_id         2000 non-null   object
 1   transaction_id   2000 non-null   object
 2   alert_type       2000 non-null   object
 3   alert_date       2000 non-null   object
 4   resolved         2000 non-null   bool
 5   resolution_date  1752 non-null   object
 6   remarks          2000 non-null   object
dtypes: bool(1), object(6)
memory usage: 95.8+ KB

In [263]:
fraud_new_df.shape

(2000, 7)

In [264]:
fraud_new_df["alert_date"] = pd.to_datetime(
    fraud_new_df["alert_date"],
    format="%d-%m-%Y %H:%M:%S"
).dt.date

In [265]:
fraud_new_df["resolution_date"] = pd.to_datetime(
    fraud_new_df["resolution_date"],
    errors="coerce"
)

C:\Users\ADMIN\AppData\Local\Temp\ipykernel_4104\1222051408.py:1: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  fraud_new_df["resolution_date"] = pd.to_datetime(

In [266]:
fraud_new_df["resolution_date"].head()

0                   NaT
1                   NaT
2   2026-07-27 23:55:54
3                   NaT
4                   NaT
Name: resolution_date, dtype: datetime64[ns]

In [257]:
import mysql.connector

conn = mysql.connector.connect(
    host="localhost",
    user="root",
    password="Shreyassneha@1303",
    database="upi_transaction_analysis"
)

cursor = conn.cursor()

print(conn.is_connected())

True

In [259]:
insert_fraud_new_query = """
INSERT INTO fraud_alert_history_new (
    alert_id,
    transaction_id,
    alert_type,
    alert_date,
    resolved,
    resolution_date,
    remarks
)
VALUES (%s, %s, %s, %s, %s, %s, %s)
"""

In [267]:
for i in range(len(fraud_new_df)):

    row = (
        fraud_new_df.iloc[i]["alert_id"],
        fraud_new_df.iloc[i]["transaction_id"],
        fraud_new_df.iloc[i]["alert_type"],
        fraud_new_df.iloc[i]["alert_date"],
        bool(fraud_new_df.iloc[i]["resolved"]),
        None if pd.isna(fraud_new_df.iloc[i]["resolution_date"])
        else fraud_new_df.iloc[i]["resolution_date"],
        fraud_new_df.iloc[i]["remarks"]
    )

    try:
        cursor.execute(insert_fraud_new_query, row)

    except Exception as e:
        print(f"❌ Error at row {i}")
        print(row)
        print(e)
        break

conn.commit()

print("🎉 Fraud New Alert History table imported successfully!")

🎉 Fraud New Alert History table imported successfully!

In [2]:
import pandas as pd
df = pd.read_csv(r"C:\Users\ADMIN\Downloads\4414701-Datasets_-_UPI_Transactions_Data_Analysis\customer_master.csv")

In [3]:
df = df[["customer_id", "risk_score"]]

In [4]:
df.head()

  customer_id  risk_score
0  cust100000        0.39
1  cust100001        0.13
2  cust100002        0.14
3  cust100003        0.07
4  cust100004        0.30

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 2 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   customer_id  10000 non-null  object
 1   risk_score   10000 non-null  float64
dtypes: float64(1), object(1)
memory usage: 156.4+ KB

In [6]:
insert_query = """
INSERT INTO customer_risk_update
(customer_id, risk_score)
VALUES (%s, %s)
"""

In [9]:
for i in range(len(df)):

    row = (
        str(df.iloc[i]["customer_id"]),
        float(df.iloc[i]["risk_score"])
    )

    try:
        cursor.execute(insert_query, row)

    except Exception as e:
        print(f"❌ Error at row {i}")
        print(row)
        print(e)
        break

❌ Error at row 0
('cust100000', 0.39)
name 'cursor' is not defined

In [11]:
import mysql.connector

conn = mysql.connector.connect(
    host="localhost",
    user="root",
    password="Shreyassneha@1303",
    database="upi_transaction_analysis"
)

cursor = conn.cursor()

print("✅ Connected successfully!")

✅ Connected successfully!

In [15]:
insert_query = """
INSERT INTO customer_risk_score_update
(customer_id, risk_score)
VALUES (%s, %s)
"""

In [16]:
for i in range(len(df)):

    row = (
        str(df.iloc[i]["customer_id"]),
        float(df.iloc[i]["risk_score"])
    )

    try:
        cursor.execute(insert_query, row)

    except Exception as e:
        print(f"❌ Error at row {i}")
        print(row)
        print(e)
        break

In [17]:
conn.commit()

print("✅ Customer risk update table imported successfully!")

✅ Customer risk update table imported successfully!

In [18]:
df = pd.read_csv(r"C:\Users\ADMIN\Downloads\4414701-Datasets_-_UPI_Transactions_Data_Analysis\merchant_info.csv")

In [19]:
df.head()

,merchant_id,merchant_name,merchant_type,region,onboard_date,risk_score
0,merch1000,Anderson Inc,grocery,north,2022-01-14,0.07
1,merch1001,"Rojas, Newton and White",online,north,2021-08-20,0.29
2,merch1002,Knox-Reyes,food,west,2024-10-29,0.20
3,merch1003,"Joseph, Serrano and Gilmore",grocery,north,2023-07-22,0.14
4,merch1004,Brown-Jones,food,north,2024-01-02,0.32

In [20]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   merchant_id    500 non-null    object
 1   merchant_name  500 non-null    object
 2   merchant_type  500 non-null    object
 3   region         500 non-null    object
 4   onboard_date   500 non-null    object
 5   risk_score     500 non-null    float64
dtypes: float64(1), object(5)
memory usage: 23.6+ KB

In [24]:
insert_query = """
insert into merchant_risk_score_update
(merchant_id, risk_score)
values (%s,%s)
"""

In [26]:
for i in range(len(df)):
    row = (
        str(df.iloc[i]["merchant_id"]),
        float(df.iloc[i]["risk_score"])
    )

    try:
        cursor.execute(insert_query, row)

    except Exception as e:
        print(f"❌ Error at row {i}")
        print(row)
        print(e)
        break

conn.commit()

print("✅ Merchant risk update table imported successfully!")

❌ Error at row 0
('merch1000', 0.07)
1062 (23000): Duplicate entry 'merch1000' for key 'merchant_risk_score_update.PRIMARY'
✅ Merchant risk update table imported successfully!

In [27]:
print((df["risk_score"] == 0).sum())

34